#!/bin/bash
#
# Copyright (c) 2016, mar77i <mysatyre at gmail dot com>
#
# This software may be modified and distributed under the terms
# of the ISC license.  See the LICENSE file for details.

apikeyfile="/etc/afraiddns/apikey"

echo Updating Afraid.org DNS
curl -sk "https://freedns.afraid.org/dynamic/update.php?$(<$apikeyfile)"
