#!/bin/bash
#
# Copyright (c) 2016, mar77i <mysatyre at gmail dot com>
#
# This software may be modified and distributed under the terms
# of the ISC license.  See the LICENSE file for details.

apikeyfile="/etc/afraiddns/apikey"

echo Updating Afraid.org DNS
while read line; do
	curl -s "https://freedns.afraid.org/dynamic/update.php?${line}"
done <"$apikeyfile"
